POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpZCI6IjY3YWE0OTI3OTUxZGI3YjIzYjY2ZmYwZiIsImlhdCI6MTczOTMxNjM0MH0.rQugSjXMIdRa0eArZMxj9p9XO-NYu_0z1wf4Ird2gHE

{
    "title": "after user extraction in middleware",
    "author": "user the one",
    "url": "firstbearer.blog.org",
    "likes": 10
}